[build.environment]
  PYTHON_VERSION = "3.11"

[build]
  command = "sudo apt-get update && apt-get install -y gfortran && pip install -r requirements.txt"
  publish = "."

[build.processing]
  skip = false

[functions]
  directory = "functions"
