[build.environment]
  PYTHON_VERSION = "3.11"

[build]
  apt = ["gfortran"]
  command = "pip install -r requirements.txt"
  publish = "."


[build.processing]
  skip = false

[functions]
  directory = "functions"
